site_name: SAHD
site_description: >-
    Semantics of Ancient Hebrew Database.
site_url: 'https://vesaakerman.github.io/sahd/'
site_author: Vesa Åkerman

nav:
    - Home: index.md
    - Words:
            - א:
                - אָזֵן - weapon: words/weapon.md
                - אַח - brazier: words/brazier.md
            - ב:
                - בַּיִת - house: words/house.md
    - Semantic fields:
            - Something 1: semantic_fields/something_1.md
            - Something 2: semantic_fields/something_2.md
    - Contributors:
            - Beentjes Pancratius: contributors/beentjes_pancratius.md
            - Korpel Marjo: contributors/korpel_marjo.md
            - Koster Marinus: contributors/koster_marinus.md
    - Partners: 'miscellaneous/partners.md'
    - Contribution: 'miscellaneous/contribution.md'
    - Contact: 'miscellaneous/contact.md'

theme:
    name: material

markdown_extensions:
    - attr_list
    - footnotes
    - md_in_html

extra_css:
   - stylesheets/extra.css

extra_javascript:
    - javascripts/extra.js


